# Generated by Django 3.1.2 on 2021-01-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authorization', '0002_auto_20210109_2250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomGroup',
            new_name='Group',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(default='964986', unique=True),
        ),
    ]
