# Generated by Django 3.1.2 on 2021-01-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_auto_20210109_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(default='340841', unique=True),
        ),
    ]
