# Generated by Django 3.1.2 on 2021-01-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Вид',
                'verbose_name_plural': 'Добавить вид',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=13, verbose_name='Кличка')),
                ('description', models.TextField(verbose_name='О питомце')),
                ('receipt_date', models.DateField(auto_now=True, verbose_name='Поступил')),
                ('face', models.ImageField(blank=True, upload_to='pets_foto', verbose_name='Фотография')),
                ('birth_data', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('Мальчик', 'Мальчик'), ('Девочка', 'Девочка')], max_length=10, null=True, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Добавить животное',
            },
        ),
    ]
