# Generated by Django 3.1.2 on 2020-12-25 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kind',
            options={'verbose_name': 'Вид', 'verbose_name_plural': 'Добавить вид'},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Животное', 'verbose_name_plural': 'Добавить животное'},
        ),
    ]
